name: earthquake_detector_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.3
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/maps/
  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun/Sarabun-Bold.ttf
          weight: 700